-- Backup UserCubeSummary and EventCubeSummary
CREATE TABLE EventCube.UserCubeSummary_20160420 AS
SELECT * FROM EventCube.UserCubeSummary;

CREATE TABLE EventCube.EventCubeSummary_20160420 AS
SELECT * FROM EventCube.EventCubeSummary;

SELECT COUNT(*) FROM EventCube.UserCubeSummary_20160420;
-- US: 2120352
-- EU: 177176

SELECT COUNT(*) FROM EventCube.UserCubeSummary;
-- US: 2120352
-- EU: 177176

-- Recreate Tables with New Structures

DROP TABLE IF EXISTS EventCube.DimEvents; 
CREATE TABLE EventCube.DimEvents (
applicationid character varying,
name text,
startdate date,
enddate date,
openevent integer,
leadscanning integer,
surveyson integer,
interactivemap integer,
leaderboard integer,
bookmarking integer,
photofeed integer,
attendeeslist integer,
qrcode integer,
DirectMessaging integer,
TopicChannel integer,
exhibitorreqinfo integer,
exhibitormsg integer,
privatemsging integer,
peoplematching integer,
socialnetworks integer,
ratingson integer,
NativeSessionNotes integer,
SessionChannel integer,
SessionRecommendations integer,
PeopleRecommendations integer
)
;


DROP TABLE IF EXISTS EventCube.UserCubeSummary;
CREATE TABLE EventCube.UserCubeSummary (
applicationid character varying,
name text,
startdate date,
enddate date,
globaluserid character varying,
userid integer,
firsttimestamp timestamp without time zone,
lasttimestamp timestamp without time zone,
facebook integer,
twitter integer,
linkedin integer,
device text,
devicetype text,
binaryversion text,
active integer,
engaged integer,
sessions bigint,
eventsessions bigint,
posts bigint,
postsimage bigint,
postsitem bigint,
likes bigint,
comments bigint,
totalbookmarks bigint,
importedbookmarks bigint,
follows bigint,
checkins bigint,
checkinsheadcount bigint,
ratings bigint,
reviews bigint,
surveys bigint,
openevent integer,
leadscanning integer,
surveyson integer,
interactivemap integer,
leaderboard integer,
bookmarking integer,
photofeed integer,
attendeeslist integer,
qrcode integer,
directmessaging integer,
topicchannel integer,
exhibitorreqinfo integer,
exhibitormsg integer,
privatemsging integer,
peoplematching integer,
socialnetworks integer,
ratingson integer,
nativesessionnotes integer,
SessionChannel integer,
SessionRecommendations integer,
PeopleRecommendations integer,
eventtype text,
eventsize text,
accountcustomerdomain text,
servicetiername text,
app365indicator text,
ownername text,
created timestamp without time zone,
updated timestamp without time zone
)
;

DROP INDEX IF EXISTS ndx_usercubesummary;
CREATE INDEX ndx_usercubesummary ON EventCube.UserCubeSummary(userid);

DROP TABLE IF EXISTS EventCube.STG_UserCubeSummary;
CREATE TABLE EventCube.STG_UserCubeSummary (
applicationid character varying,
name text,
startdate date,
enddate date,
globaluserid character varying,
userid integer,
firsttimestamp timestamp without time zone,
lasttimestamp timestamp without time zone,
facebook integer,
twitter integer,
linkedin integer,
device text,
devicetype text,
binaryversion text,
active integer,
engaged integer,
sessions bigint,
eventsessions bigint,
posts bigint,
postsimage bigint,
postsitem bigint,
likes bigint,
comments bigint,
totalbookmarks bigint,
importedbookmarks bigint,
follows bigint,
checkins bigint,
checkinsheadcount bigint,
ratings bigint,
reviews bigint,
surveys bigint,
openevent integer,
leadscanning integer,
surveyson integer,
interactivemap integer,
leaderboard integer,
bookmarking integer,
photofeed integer,
attendeeslist integer,
qrcode integer,
directmessaging integer,
topicchannel integer,
exhibitorreqinfo integer,
exhibitormsg integer,
privatemsging integer,
peoplematching integer,
socialnetworks integer,
ratingson integer,
nativesessionnotes integer,
SessionChannel integer,
SessionRecommendations integer,
PeopleRecommendations integer,
eventtype text,
eventsize text,
accountcustomerdomain text,
servicetiername text,
app365indicator text,
ownername text
)
;

DROP INDEX IF EXISTS ndx_stg_usercubesummary;
CREATE INDEX ndx_stg_usercubesummary ON EventCube.STG_UserCubeSummary(userid);

DROP TABLE IF EXISTS EventCube.STG_UserCubeSummary_INSERT;
CREATE TABLE EventCube.STG_UserCubeSummary_INSERT (
applicationid character varying,
name text,
startdate date,
enddate date,
globaluserid character varying,
userid integer,
firsttimestamp timestamp without time zone,
lasttimestamp timestamp without time zone,
facebook integer,
twitter integer,
linkedin integer,
device text,
devicetype text,
binaryversion text,
active integer,
engaged integer,
sessions bigint,
eventsessions bigint,
posts bigint,
postsimage bigint,
postsitem bigint,
likes bigint,
comments bigint,
totalbookmarks bigint,
importedbookmarks bigint,
follows bigint,
checkins bigint,
checkinsheadcount bigint,
ratings bigint,
reviews bigint,
surveys bigint,
openevent integer,
leadscanning integer,
surveyson integer,
interactivemap integer,
leaderboard integer,
bookmarking integer,
photofeed integer,
attendeeslist integer,
qrcode integer,
directmessaging integer,
topicchannel integer,
exhibitorreqinfo integer,
exhibitormsg integer,
privatemsging integer,
peoplematching integer,
socialnetworks integer,
ratingson integer,
nativesessionnotes integer,
SessionChannel integer,
SessionRecommendations integer,
PeopleRecommendations integer,
eventtype text,
eventsize text,
accountcustomerdomain text,
servicetiername text,
app365indicator text,
ownername text
)
;

DROP TABLE IF EXISTS EventCube.STG_UserCubeSummary_UPDATE;
CREATE TABLE EventCube.STG_UserCubeSummary_UPDATE (
applicationid character varying,
name text,
startdate date,
enddate date,
globaluserid character varying,
userid integer,
firsttimestamp timestamp without time zone,
lasttimestamp timestamp without time zone,
facebook integer,
twitter integer,
linkedin integer,
device text,
devicetype text,
binaryversion text,
active integer,
engaged integer,
sessions bigint,
eventsessions bigint,
posts bigint,
postsimage bigint,
postsitem bigint,
likes bigint,
comments bigint,
totalbookmarks bigint,
importedbookmarks bigint,
follows bigint,
checkins bigint,
checkinsheadcount bigint,
ratings bigint,
reviews bigint,
surveys bigint,
openevent integer,
leadscanning integer,
surveyson integer,
interactivemap integer,
leaderboard integer,
bookmarking integer,
photofeed integer,
attendeeslist integer,
qrcode integer,
directmessaging integer,
topicchannel integer,
exhibitorreqinfo integer,
exhibitormsg integer,
privatemsging integer,
peoplematching integer,
socialnetworks integer,
ratingson integer,
nativesessionnotes integer,
SessionChannel integer,
SessionRecommendations integer,
PeopleRecommendations integer,
eventtype text,
eventsize text,
accountcustomerdomain text,
servicetiername text,
app365indicator text,
ownername text
)
;

DROP TABLE IF EXISTS EventCube.EventCubeSummary CASCADE;
CREATE TABLE EventCube.EventCubeSummary (
applicationid character varying,
name text,
startdate date,
enddate date,
binaryversion text,
openevent integer,
leadscanning integer,
surveyson integer,
interactivemap integer,
leaderboard integer,
bookmarking integer,
photofeed integer,
attendeeslist integer,
qrcode integer,
directmessaging integer,
topicchannels integer,
exhibitorreqinfo integer,
exhibitormsg integer,
privatemsging integer,
peoplematching integer,
socialnetworks integer,
ratingson integer,
nativesessionnotes integer,
SessionChannel integer,
SessionRecommendations integer,
PeopleRecommendations integer,
eventtype text,
eventsize text,
accountcustomerdomain text,
servicetiername text,
app365indicator text,
ownername text,
registrants bigint,
uniquedevices bigint,
users bigint,
usersactive bigint,
usersengaged bigint,
usersfacebook bigint,
userstwitter bigint,
userslinkedin bigint,
sessions numeric,
eventsessions numeric,
posts numeric,
postsimage numeric,
postsitem numeric,
likes numeric,
comments numeric,
totalbookmarks numeric,
importedbookmarks numeric,
follows numeric,
checkins numeric,
checkinsheadcount numeric,
ratings numeric,
reviews numeric,
surveys numeric,
promotedposts bigint,
globalpushnotifications bigint,
exhibitors bigint,
polls numeric,
pollresponses numeric,
topicchannelcnt numeric,
directmessagingsentcnt numeric,
topicchannelmsgsentcnt numeric,
sessionchannelmsgsentcnt numeric,
adoption numeric,
eventsessionsperusersperday numeric
)
;

-- Load UserCube Backup Data into new UserCube table
INSERT INTO EventCube.UserCubeSummary (
SELECT 
applicationid,
name,
startdate,
enddate,
globaluserid,
userid,
firsttimestamp,
lasttimestamp,
facebook,
twitter,
linkedin,
device,
devicetype,
binaryversion,
active,
engaged,
sessions,
null as eventsessions,
posts,
postsimage,
postsitem,
likes,
comments,
totalbookmarks,
importedbookmarks,
follows,
checkins,
checkinsheadcount,
ratings,
reviews,
surveys,
openevent,
leadscanning,
surveyson,
interactivemap,
leaderboard,
bookmarking,
photofeed,
attendeeslist,
qrcode,
0 as directmessaging,
0 as topicchannel,
exhibitorreqinfo,
exhibitormsg,
privatemsging,
peoplematching,
socialnetworks,
ratingson,
0 as nativesessionnotes,
0 as sessionchannel,
0 as sessionrecommendations,
0 as peoplerecommendations,
eventtype,
eventsize,
accountcustomerdomain,
servicetiername,
app365indicator,
ownername,
created,
updated  
FROM EventCube.UserCubeSummary_20160420);



alter table eventcube.eventcubesummary rename column topicchannels to topicchannel;