
--======================================================================================================
--Create the schema
CREATE SCHEMA olessia;

--Create the read-only user for the views
CREATE USER olessia LOGIN PASSWORD 'd0u813du7cH_olessia';
--ALTER USER dylan WITH PASSWORD 'd0u813du7cH_dylan';

-- Reset Password
--ALTER USER rterry PASSWORD 'terry123';

--Grant CONNECT ON DATABASE
GRANT CONNECT ON DATABASE analytics TO olessia;

-- Grant USAGE ON SCHEMAS
GRANT USAGE ON SCHEMA PUBLIC TO olessia;
GRANT USAGE ON SCHEMA eventcube TO olessia;
GRANT USAGE ON SCHEMA channels TO olessia;
GRANT USAGE ON SCHEMA mailgun TO olessia;
GRANT USAGE ON SCHEMA google TO olessia;
GRANT USAGE ON SCHEMA dashboard TO olessia;
GRANT USAGE ON SCHEMA secondside TO olessia;
GRANT USAGE ON SCHEMA integrations TO olessia;
GRANT USAGE ON SCHEMA mandrill TO olessia;
GRANT USAGE ON SCHEMA marketo TO olessia;
GRANT USAGE ON SCHEMA salesforce TO olessia;
GRANT USAGE ON SCHEMA rterry TO olessia;
GRANT USAGE ON SCHEMA report TO olessia;

-- Grant SELECT ON ALL TABLES IN SCHEMA
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA eventcube TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA channels TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA mailgun TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA google TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA dashboard TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA secondside TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA integrations TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA mandrill TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA marketo TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA salesforce TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA rterry TO olessia;
GRANT SELECT ON ALL TABLES IN SCHEMA report TO olessia;

-- ALTER DEFAULT PRIVILEGES
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA eventcube GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA channels GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA mailgun GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA google GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA dashboard GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA secondside GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA integrations GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA mandrill GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA marketo GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA salesforce GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA rterry GRANT SELECT ON TABLES TO olessia;
ALTER DEFAULT PRIVILEGES IN SCHEMA report GRANT SELECT ON TABLES TO olessia;

-- GRANT ALL ON OWN SCHEMA
GRANT ALL ON SCHEMA olessia to olessia;

-- COMMIT CHANGES
COMMIT;


--- SSH Setup
-- Login into robin using jteruya username (sudo access)
-- sudo useradd -m olessia
-- sudo passwd olessia